### ISSUE TITLE
issue running the program

### ISSUE THREAD

**Issue by paulrod0** [techwithtim/NEAT-Flappy-Bird#2]
that what it show in terminal:
multiple errors with the configparser

Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'max_fitness_threshold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablolopezrodriguez/Downloads/Comprimidos/NEAT-Flappy-Bird-master/flappy_bird.py", line 441, in <module>
    run(config_path)
  File "/Users/pablolopezrodriguez/Downloads/Comprimidos/NEAT-Flappy-Bird-master/flappy_bird.py", line 417, in run
    config_file)
  File "/usr/local/lib/python3.7/site-packages/neat/config.py", line 103, in __init__
    setattr(self, p.name, p.parse('NEAT', parameters))
  File "/usr/local/lib/python3.7/site-packages/neat/config.py", line 23, in parse
    return config_parser.getfloat(section, self.name)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 823, in getfloat
    fallback=fallback, **kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'max_fitness_threshold' in section: 'NEAT'

**Comment by adneovrebo** [comment]
Just add:
max_fitness_threshold = 100 
to config-feedforwar.txt under [NEAT] 

Change this line:
p.add_reporter(neat.StdOutReporter(True)) =>     p.add_reporter(neat.StdOutReporter())
