### ISSUE TITLE
pygame 1.9.6 Hello from the pygame community. https://www.pygame.org/contribute.html Traceback (most recent call last):   File "c:/Users/ahmad/Desktop/Python/NEAT-Flappy-Bird-master/flappy_bird.py", line 441, in <module>     run(config_path)   File "c:/Users/ahmad/Desktop/Python/NEAT-Flappy-Bird-master/flappy_bird.py", line 415, in run     config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction, AttributeError: module 'neat' has no attribute 'Config'

### ISSUE THREAD

**Issue by carmonkeylab** [techwithtim/NEAT-Flappy-Bird#22]
i fixed some of the other errors i had but now i get this `pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/ahmad/Desktop/Python/NEAT-Flappy-Bird-master/flappy_bird.py", line 441, in <module>
    run(config_path)
  File "c:/Users/ahmad/Desktop/Python/NEAT-Flappy-Bird-master/flappy_bird.py", line 415, in run
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: module 'neat' has no attribute 'Config'`

**Comment by carmonkeylab** [comment]
uninstalled and reinstalled neat fixed the issue
